trigger:
  branches:
    include:
      - Staging
      - master

pool:
  name: Default

variables:
  repoUrl: 'https://github.com/souravb-smu/odoo17.git'
  updateScript: '$HOME/deploy-temp/update_code.sh'
  stagePath: '$HOME'

stages:

# =========================
# STAGING STAGE
# =========================
- stage: Staging
  displayName: Deploy to Staging
  condition: eq(variables['Build.SourceBranchName'], 'Staging')

  jobs:
  - deployment: DeployStaging
    environment: Staging
    strategy:
      runOnce:
        deploy:
          steps:

          - task: SSH@0
            displayName: "Sync Code - Staging"
            inputs:
              sshEndpoint: 'ssh-odoo17'
              runOptions: commands
              commands: |
                set -e
                echo "Deploying branch: $(Build.SourceBranchName)"
                cd $HOME

                rm -rf deploy-temp *-odoo17

                git clone -b Staging $(repoUrl) --quiet
                mv *-odoo17 deploy-temp

                cd deploy-temp
                rm -f .DS_Store
                rm -rf .github

          - task: SSH@0
            displayName: "Run Update Script - Staging"
            inputs:
              sshEndpoint: 'ssh-odoo17'
              runOptions: commands
              commands: |
                set -e
                chmod +x $HOME/deploy-temp/update_code.sh
                echo "$(STAGINGUSERPASSWORD)" | sudo -S -p '' $HOME/deploy-temp/update_code.sh


# =========================
# PRODUCTION STAGE
# =========================
- stage: Production
  displayName: Deploy to Production
  condition: eq(variables['Build.SourceBranchName'], 'master')

  jobs:
  - deployment: DeployProduction
    environment: Production
    strategy:
      runOnce:
        deploy:
          steps:

          - task: SSH@0
            displayName: "Sync Code - Production"
            inputs:
              sshEndpoint: 'ssh-odoo17-production'
              runOptions: commands
              commands: |
                set -e
                echo "Deploying branch: $(Build.SourceBranchName)"
                cd $HOME

                rm -rf deploy-temp *-odoo17

                git clone -b master $(repoUrl) --quiet
                mv *-odoo17 deploy-temp

                cd deploy-temp
                rm -f .DS_Store
                rm -rf .github

          - task: SSH@0
            displayName: "Uncompress odoo.sql.gz on VM"
            inputs:
              sshEndpoint: 'ssh-odoo17-production'
              runOptions: commands
              commands: |
                set -e
                cd $HOME/deploy-temp

                echo "Uncompressing odoo.sql.gz..."
                gunzip -c odoo.sql.gz > odoo.sql
                echo "Uncompress complete"

          - task: SSH@0
            displayName: "Restore Database"
            inputs:
              sshEndpoint: 'ssh-odoo17-production'
              runOptions: commands
              commands: |
                set -e

                echo "$(STAGINGUSERPASSWORD)" | sudo -S -p '' cp $HOME/deploy-temp/restore_db.sh /tmp/
                echo "$(STAGINGUSERPASSWORD)" | sudo -S -p '' cp $HOME/deploy-temp/odoo.sql /tmp/

                echo "$(STAGINGUSERPASSWORD)" | sudo -S -p '' chmod +x /tmp/restore_db.sh
                echo "$(STAGINGUSERPASSWORD)" | sudo -S -p '' chmod 644 /tmp/odoo.sql

                echo "$(STAGINGUSERPASSWORD)" | sudo -S -p '' -u postgres /tmp/restore_db.sh "odoo17" "odoo" "/tmp/odoo.sql"

          - task: SSH@0
            displayName: "Run Update Script - Production"
            inputs:
              sshEndpoint: 'ssh-odoo17-production'
              runOptions: commands
              commands: |
                set -e
                chmod +x $HOME/deploy-temp/update_code.sh
                echo "$(STAGINGUSERPASSWORD)" | sudo -S -p '' $HOME/deploy-temp/update_code.sh